package com.ceylonapz.profitbook.model

data class Order(val orderId: Long,
                 val symbol: String,
                 val status: String,
                 val clientOrderId: String,
                 val price: String,
                 val avgPrice: String,
                 val origQty: String,
                 val executedQty: String,
                 val cumQty: String,
                 val cumQuote: String,
                 val timeInForce: String,
                 val type: String,
                 val reduceOnly: Boolean,
                 val closePosition: Boolean,
                 val side: String,
                 val positionSide: String,
                 val stopPrice: String,
                 val workingType: String,
                 val priceProtect: Boolean,
                 val origType: String,
                 val priceMatch: String,
                 val selfTradePreventionMode: String,
                 val goodTillDate: Long,
                 val updateTime: Long)
